// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbraeqykitkqzrngynxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5icmFlcXlraXRrcXpybmd5bnhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzA3MDgsImV4cCI6MjA2NjgwNjcwOH0.irjTHZav3jC_RETfBmE2MoEZWibFoyOMxjxmHOag2hM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});